"""The plugin host's test fixture: wire v0 over stdin and stdout.

It lists one collection of three tracks and serves generated bytes, byte i
being i % 251. What it does besides comes from the config `hello` carries,
so each test sets its own:

  size           bytes per track (default 1 MiB)
  unseekable     answer seekable: false
  page           tracks per sync page (default 2)
  sleep          {method: seconds} to wait before answering
  crash_on       a method that makes it exit without answering
  hello_crash    exit during hello instead
  loop_file      a file the endless "live" key plays over and over; also
                 lists a live track in the collection
  live_kbps      how fast the live key's bytes come (default 128)

A key starting with "live" is an endless live stream: generated bytes, or
`loop_file` looped, paced at `live_kbps`. It exits when stdin closes.
"""

import base64
import json
import os
import sys
import threading
import time

TRACKS = [
    {"key": f"t{i}", "title": f"Tone {i}", "artist": "Echo", "album": "Fixtures",
     "track_no": i, "duration_ms": 1000, "codec": "", "bitrate_kbps": 0, "live": False}
    for i in (1, 2, 3)
]

LIVE = {"key": "live", "title": "Echo live", "artist": "Echo", "album": "Fixtures",
        "track_no": 0, "duration_ms": 0, "codec": "", "bitrate_kbps": 0, "live": True}

config = {}
out_lock = threading.Lock()
streams = {}
streams_lock = threading.Lock()
next_stream = [0]


def send(frame):
    line = json.dumps(frame, separators=(",", ":")) + "\n"
    with out_lock:
        sys.stdout.write(line)
        sys.stdout.flush()


def tracks():
    return TRACKS + ([LIVE] if config.get("loop_file") else [])


def pattern(offset, count):
    return bytes((offset + i) % 251 for i in range(count))


def live_bytes(stream, count):
    # Answer with what a broadcast has ready, half a second of it, rather
    # than holding the read until `count` arrives: a big ask at a low
    # bitrate would outlast the host's read timeout.
    rate = max(1, int(config.get("live_kbps", 128))) * 125
    count = min(count, max(1, rate // 2))
    wait = count / rate - (time.monotonic() - stream["last"])
    if wait > 0:
        time.sleep(wait)
    stream["last"] = time.monotonic()

    looped = stream.get("loop")
    if looped is None:
        data = pattern(stream["pos"], count)
    else:
        data = bytearray()
        while len(data) < count:
            at = (stream["pos"] + len(data)) % len(looped)
            data += looped[at:at + count - len(data)]
        data = bytes(data)

    stream["pos"] += len(data)
    return data


def handle(rid, method, params):
    delay = config.get("sleep", {}).get(method)
    if delay:
        time.sleep(delay)

    if method == config.get("crash_on"):
        os._exit(3)

    if method == "source.browse":
        if params.get("node") is None:
            return {"entries": [{"node": {"id": "all", "title": "All", "subtitle": "three tones", "collection": True}}], "cursor": None}
        return {"entries": [{"track": t} for t in tracks()], "cursor": None}

    if method == "source.search":
        query = params.get("query", "")
        return {"entries": [{"track": t} for t in TRACKS if query in t["title"]], "cursor": None}

    if method == "source.sync":
        if params.get("token") == "v1":
            return {"unchanged": True, "tracks": [], "cursor": None, "token": None}
        page = int(config.get("page", 2))
        start = int(params.get("cursor") or 0)
        listed = tracks()
        tracks_page = listed[start:start + page]
        more = start + page < len(listed)
        return {"unchanged": False, "tracks": tracks_page, "cursor": str(start + page) if more else None,
                "token": None if more else "v1"}

    if method == "source.open":
        key = params["key"]
        with streams_lock:
            next_stream[0] += 1
            sid = f"s{next_stream[0]}"
            if key.startswith("live"):
                stream = {"live": True, "pos": 0, "last": time.monotonic()}
                if config.get("loop_file"):
                    with open(config["loop_file"], "rb") as f:
                        stream["loop"] = f.read()
            else:
                stream = {"live": False}
            streams[sid] = stream

        if stream["live"]:
            hint = os.path.splitext(config.get("loop_file", ""))[1].lstrip(".")
            return {"stream": sid, "hint": hint, "length": None, "seekable": False, "live": True}

        size = int(config.get("size", 1 << 20))
        return {"stream": sid, "hint": "", "length": size,
                "seekable": not config.get("unseekable", False), "live": False}

    if method == "source.read":
        with streams_lock:
            stream = streams.get(params["stream"])
        if stream is None:
            raise ValueError(f"no open stream {params['stream']}")

        offset, want = int(params["offset"]), int(params["len"])
        if stream["live"]:
            data = live_bytes(stream, want)
        else:
            size = int(config.get("size", 1 << 20))
            data = pattern(offset, max(0, min(want, size - offset)))
        return {"data": base64.b64encode(data).decode("ascii")}

    if method == "source.close":
        with streams_lock:
            streams.pop(params["stream"], None)
        return None

    if method == "source.cover":
        return {"mime": "image/png", "data": base64.b64encode(b"not really a png").decode("ascii")}

    raise KeyError(f"method not found: {method}")


def answer(rid, method, params):
    try:
        send({"jsonrpc": "2.0", "id": rid, "result": handle(rid, method, params)})
    except Exception as e:
        send({"jsonrpc": "2.0", "id": rid, "error": {"code": -32000, "message": f"{type(e).__name__}: {e}"}})


def main():
    for raw in sys.stdin:
        raw = raw.strip()
        if not raw:
            continue

        frame = json.loads(raw)
        rid, method, params = frame.get("id"), frame.get("method"), frame.get("params") or {}

        if method == "hello":
            config.clear()
            config.update(params.get("config") or {})
            if config.get("hello_crash"):
                os._exit(4)
            send({"jsonrpc": "2.0", "id": rid, "result": {"name": "Echo", "version": "0.1.0", "api": 0}})
            continue

        if method == "shutdown":
            send({"jsonrpc": "2.0", "id": rid, "result": None})
            os._exit(0)

        threading.Thread(target=answer, args=(rid, method, params), daemon=True).start()

    os._exit(0)


if __name__ == "__main__":
    main()
